"""Test event factories — deterministic seed data for all test layers.

All 15 events use fixed UUIDs and March 2026 dates so they always fall inside
the default 30-day timeline window. Status distribution:
  needs_review: 5  (events 1-5)
  approved:     3  (events 6-8)
  published:    3  (events 9-11)
  rejected:     2  (events 12-13)
  archived:     2  (events 14-15)
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

from src.domain.models import (
    ActionType,
    ChangeType,
    Environment,
    Event,
    EventCategory,
    EventOrigin,
    EventStatus,
    MessageSource,
    ReviewLifecycleStatus,
    Severity,
    TimeSource,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _dt(day: int, hour: int = 10, month: int = 3, year: int = 2026) -> datetime:
    return datetime(year, month, day, hour, 0, 0, tzinfo=UTC)


def _uuid(n: int) -> UUID:
    return UUID(f"00000000-0000-0000-0000-{n:012d}")


# ---------------------------------------------------------------------------
# Seed events
# ---------------------------------------------------------------------------

SEED_EVENTS: list[Event] = [
    # ---- needs_review x5 ------------------------------------------------
    Event(
        event_id=_uuid(1),
        message_id="msg-seed-001",
        source_channels=["#releases"],
        message_published_at=_dt(2),
        action=ActionType.LAUNCH,
        object_name_raw="Payments v2",
        category=EventCategory.PRODUCT,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.LAUNCH,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(2),
        planned_end=_dt(2, hour=18),
        actual_start=_dt(2),
        actual_end=_dt(2, hour=17),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="Payments v2 was successfully launched to production on March 2.",
        why_it_matters="New payment flow reduces checkout friction for all users.",
        confidence=0.87,
        importance=82,
        cluster_key="payments-v2-launch",
        dedup_key="payments-v2-launch-completed-prod-2026-03-02",
        impact_area=["payments", "checkout"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.NEEDS_REVIEW,
        origin=EventOrigin.AI_EXTRACTION,
        version=1,
    ),
    Event(
        event_id=_uuid(2),
        message_id="msg-seed-002",
        source_channels=["#incidents"],
        message_published_at=_dt(4),
        action=ActionType.INCIDENT,
        object_name_raw="Auth Service",
        category=EventCategory.RISK,
        status=EventStatus.STARTED,
        change_type=ChangeType.INCIDENT,
        environment=Environment.PROD,
        severity=Severity.SEV2,
        planned_start=None,
        planned_end=None,
        actual_start=_dt(4, hour=11),
        actual_end=None,
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.8,
        summary="SEV2 incident on Auth Service started at 11:00 UTC on March 4.",
        why_it_matters="Authentication failures affect all users attempting to log in.",
        confidence=0.72,
        importance=75,
        cluster_key="auth-service-incident",
        dedup_key="auth-service-incident-started-prod-2026-03-04",
        impact_area=["auth", "users"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.NEEDS_REVIEW,
        origin=EventOrigin.AI_EXTRACTION,
        version=1,
    ),
    Event(
        event_id=_uuid(3),
        message_id="msg-seed-003",
        source_channels=["#engineering"],
        message_published_at=_dt(5),
        action=ActionType.MIGRATION,
        object_name_raw="Database Sharding",
        category=EventCategory.PROCESS,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.MIGRATION,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(5),
        planned_end=_dt(5, hour=20),
        actual_start=_dt(5),
        actual_end=_dt(5, hour=19),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="Database sharding migration completed successfully on March 5.",
        why_it_matters="Sharding improves read/write throughput by 3x.",
        confidence=0.83,
        importance=68,
        cluster_key="db-sharding-migration",
        dedup_key="db-sharding-migration-completed-prod-2026-03-05",
        impact_area=["database", "infrastructure"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.NEEDS_REVIEW,
        origin=EventOrigin.AI_EXTRACTION,
        version=1,
    ),
    Event(
        event_id=_uuid(4),
        message_id="msg-seed-004",
        source_channels=["@tech_news"],
        message_published_at=_dt(7),
        action=ActionType.LAUNCH,
        object_name_raw="Mobile App v3",
        category=EventCategory.PRODUCT,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.LAUNCH,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(7),
        planned_end=_dt(7, hour=20),
        actual_start=_dt(7),
        actual_end=_dt(7, hour=18),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.85,
        summary="Mobile App v3 launched with redesigned navigation and dark mode support.",
        why_it_matters="Redesign addresses top user complaints and improves DAU metrics.",
        confidence=0.78,
        importance=91,
        cluster_key="mobile-app-v3-launch",
        dedup_key="mobile-app-v3-launch-completed-prod-2026-03-07",
        impact_area=["mobile", "users"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.NEEDS_REVIEW,
        origin=EventOrigin.AI_EXTRACTION,
        version=1,
    ),
    Event(
        event_id=_uuid(5),
        message_id="msg-seed-005",
        source_channels=["@company_news"],
        message_published_at=_dt(8),
        action=ActionType.POLICY,
        object_name_raw="Remote Work Policy",
        category=EventCategory.ORG,
        status=EventStatus.CONFIRMED,
        change_type=ChangeType.POLICY,
        environment=Environment.UNKNOWN,
        severity=None,
        planned_start=_dt(8),
        planned_end=None,
        actual_start=None,
        actual_end=None,
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.7,
        summary="New remote work policy confirmed: 3 days in-office per week starting April.",
        why_it_matters="Policy change affects all employees and requires updated travel budgets.",
        confidence=0.65,
        importance=55,
        cluster_key="remote-work-policy",
        dedup_key="remote-work-policy-confirmed-2026-03-08",
        impact_area=["hr", "operations"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.NEEDS_REVIEW,
        origin=EventOrigin.AI_EXTRACTION,
        version=1,
    ),
    # ---- approved x3 ----------------------------------------------------
    Event(
        event_id=_uuid(6),
        message_id="msg-seed-006",
        source_channels=["#marketing"],
        message_published_at=_dt(10),
        action=ActionType.CAMPAIGN,
        object_name_raw="Spring Promo",
        category=EventCategory.MARKETING,
        status=EventStatus.PLANNED,
        change_type=ChangeType.CAMPAIGN,
        environment=Environment.UNKNOWN,
        severity=None,
        planned_start=_dt(15),
        planned_end=_dt(31),
        actual_start=None,
        actual_end=None,
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.8,
        summary="Spring promotional campaign planned for second half of March.",
        why_it_matters="Q1 revenue target depends on campaign performance.",
        confidence=0.80,
        importance=62,
        cluster_key="spring-promo-campaign",
        dedup_key="spring-promo-campaign-planned-2026-03-10",
        impact_area=["marketing", "revenue"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.APPROVED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(11),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    Event(
        event_id=_uuid(7),
        message_id="msg-seed-007",
        source_channels=["#deployments"],
        message_published_at=_dt(11),
        action=ActionType.DEPLOY,
        object_name_raw="API Gateway v2",
        category=EventCategory.PRODUCT,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.DEPLOY,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(11),
        planned_end=_dt(11, hour=18),
        actual_start=_dt(11),
        actual_end=_dt(11, hour=17),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="API Gateway v2 deployed to production, replacing legacy routing layer.",
        why_it_matters="Reduces P99 latency by 40ms and enables rate-limiting per tenant.",
        confidence=0.91,
        importance=78,
        cluster_key="api-gateway-v2-deploy",
        dedup_key="api-gateway-v2-deploy-completed-prod-2026-03-11",
        impact_area=["api", "infrastructure"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.APPROVED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(12),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    Event(
        event_id=_uuid(8),
        message_id="msg-seed-008",
        source_channels=["@payments_alerts"],
        message_published_at=_dt(12),
        action=ActionType.INCIDENT,
        object_name_raw="Payment Outage",
        category=EventCategory.RISK,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.INCIDENT,
        environment=Environment.PROD,
        severity=Severity.SEV1,
        planned_start=None,
        planned_end=None,
        actual_start=_dt(12, hour=16),
        actual_end=_dt(12, hour=20),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="SEV1 payment outage on March 12 lasted 4 hours, resolved by midnight.",
        why_it_matters="Affected 15% of transactions; post-mortem scheduled for March 19.",
        confidence=0.88,
        importance=85,
        cluster_key="payment-outage-march",
        dedup_key="payment-outage-march-completed-prod-2026-03-12",
        impact_area=["payments", "revenue"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.APPROVED,
        reviewed_by="reviewer-2",
        reviewed_at=_dt(13),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    # ---- published x3 ---------------------------------------------------
    Event(
        event_id=_uuid(9),
        message_id="msg-seed-009",
        source_channels=["#product"],
        message_published_at=_dt(14),
        action=ActionType.LAUNCH,
        object_name_raw="Analytics Dashboard",
        category=EventCategory.PRODUCT,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.LAUNCH,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(14),
        planned_end=_dt(14, hour=18),
        actual_start=_dt(14),
        actual_end=_dt(14, hour=17),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="Analytics Dashboard launched for all enterprise customers on March 14.",
        why_it_matters="Enables self-serve reporting, reducing support ticket volume.",
        confidence=0.93,
        importance=70,
        cluster_key="analytics-dashboard-launch",
        dedup_key="analytics-dashboard-launch-completed-prod-2026-03-14",
        impact_area=["analytics", "customers"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.PUBLISHED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(15),
        origin=EventOrigin.HUMAN_REVIEW,
        version=3,
    ),
    Event(
        event_id=_uuid(10),
        message_id="msg-seed-010",
        source_channels=["@marketing_channel"],
        message_published_at=_dt(15),
        action=ActionType.WEBINAR,
        object_name_raw="Q2 Marketing Kick-off",
        category=EventCategory.MARKETING,
        status=EventStatus.STARTED,
        change_type=ChangeType.OTHER,
        environment=Environment.UNKNOWN,
        severity=None,
        planned_start=_dt(15, hour=14),
        planned_end=_dt(15, hour=16),
        actual_start=_dt(15, hour=14),
        actual_end=None,
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.85,
        summary="Q2 Marketing Kick-off webinar started on March 15 with 200 attendees.",
        why_it_matters="Sets OKRs and messaging priorities for Q2 campaigns.",
        confidence=0.75,
        importance=58,
        cluster_key="q2-marketing-kickoff",
        dedup_key="q2-marketing-kickoff-started-2026-03-15",
        impact_area=["marketing", "brand"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.PUBLISHED,
        reviewed_by="reviewer-2",
        reviewed_at=_dt(16),
        origin=EventOrigin.HUMAN_REVIEW,
        version=3,
    ),
    Event(
        event_id=_uuid(11),
        message_id="msg-seed-011",
        source_channels=["@infrastructure"],
        message_published_at=_dt(17),
        action=ActionType.MIGRATION,
        object_name_raw="Infrastructure to AWS",
        category=EventCategory.PROCESS,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.MIGRATION,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(17),
        planned_end=_dt(20),
        actual_start=_dt(17),
        actual_end=_dt(19),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.9,
        summary="Full infrastructure migration to AWS completed ahead of schedule on March 19.",
        why_it_matters="Reduces infrastructure costs by 30% and enables auto-scaling.",
        confidence=0.89,
        importance=88,
        cluster_key="infra-aws-migration",
        dedup_key="infra-aws-migration-completed-prod-2026-03-17",
        impact_area=["infrastructure", "cost"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.PUBLISHED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(20),
        origin=EventOrigin.HUMAN_REVIEW,
        version=3,
    ),
    # ---- rejected x2 ----------------------------------------------------
    Event(
        event_id=_uuid(12),
        message_id="msg-seed-012",
        source_channels=["#deployments"],
        message_published_at=_dt(19),
        action=ActionType.DEPLOY,
        object_name_raw="Frontend Hotfix",
        category=EventCategory.UNKNOWN,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.DEPLOY,
        environment=Environment.PROD,
        severity=None,
        planned_start=_dt(19),
        planned_end=_dt(19, hour=14),
        actual_start=_dt(19),
        actual_end=_dt(19, hour=13),
        time_source=TimeSource.TS_FALLBACK,
        time_confidence=0.4,
        summary="Minor frontend hotfix deployed on March 19, low significance.",
        why_it_matters=None,
        confidence=0.45,
        importance=30,
        cluster_key="frontend-hotfix-deploy",
        dedup_key="frontend-hotfix-deploy-completed-prod-2026-03-19",
        impact_area=["frontend"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.REJECTED,
        reviewed_by="reviewer-2",
        reviewed_at=_dt(19, hour=15),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    Event(
        event_id=_uuid(13),
        message_id="msg-seed-013",
        source_channels=["@security_alerts"],
        message_published_at=_dt(20),
        action=ActionType.INCIDENT,
        object_name_raw="DDoS Attack",
        category=EventCategory.RISK,
        status=EventStatus.ROLLED_BACK,
        change_type=ChangeType.INCIDENT,
        environment=Environment.PROD,
        severity=Severity.SEV1,
        planned_start=None,
        planned_end=None,
        actual_start=_dt(20, hour=10),
        actual_end=_dt(20, hour=14),
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.85,
        summary="DDoS attack on March 20 mitigated in 4 hours via Cloudflare rules.",
        why_it_matters=None,
        confidence=0.60,
        importance=90,
        cluster_key="ddos-attack-march",
        dedup_key="ddos-attack-march-rolledback-prod-2026-03-20",
        impact_area=["security", "infrastructure"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.REJECTED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(20, hour=16),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    # ---- archived x2 ----------------------------------------------------
    Event(
        event_id=_uuid(14),
        message_id="msg-seed-014",
        source_channels=["#compliance"],
        message_published_at=_dt(22),
        action=ActionType.POLICY,
        object_name_raw="Security Compliance v2",
        category=EventCategory.PROCESS,
        status=EventStatus.COMPLETED,
        change_type=ChangeType.POLICY,
        environment=Environment.UNKNOWN,
        severity=None,
        planned_start=_dt(22),
        planned_end=None,
        actual_start=_dt(22),
        actual_end=None,
        time_source=TimeSource.EXPLICIT,
        time_confidence=0.8,
        summary="Security Compliance v2 policy completed review and archived.",
        why_it_matters=None,
        confidence=0.82,
        importance=65,
        cluster_key="security-compliance-v2",
        dedup_key="security-compliance-v2-completed-2026-03-22",
        impact_area=["security", "compliance"],
        source_id=MessageSource.SLACK,
        review_status=ReviewLifecycleStatus.ARCHIVED,
        reviewed_by="reviewer-2",
        reviewed_at=_dt(23),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
    Event(
        event_id=_uuid(15),
        message_id="msg-seed-015",
        source_channels=["@company_news"],
        message_published_at=_dt(23),
        action=ActionType.OTHER,
        object_name_raw="Engineering Restructure",
        category=EventCategory.ORG,
        status=EventStatus.CONFIRMED,
        change_type=ChangeType.OTHER,
        environment=Environment.UNKNOWN,
        severity=None,
        planned_start=_dt(23),
        planned_end=None,
        actual_start=None,
        actual_end=None,
        time_source=TimeSource.RELATIVE,
        time_confidence=0.65,
        summary="Engineering org restructure announced: teams re-aligned to product pillars.",
        why_it_matters=None,
        confidence=0.71,
        importance=50,
        cluster_key="engineering-restructure-march",
        dedup_key="engineering-restructure-march-confirmed-2026-03-23",
        impact_area=["engineering", "hr"],
        source_id=MessageSource.TELEGRAM,
        review_status=ReviewLifecycleStatus.ARCHIVED,
        reviewed_by="reviewer-1",
        reviewed_at=_dt(24),
        origin=EventOrigin.HUMAN_REVIEW,
        version=2,
    ),
]

# ---------------------------------------------------------------------------
# Counts by status (for assertions in tests)
# ---------------------------------------------------------------------------
SEED_COUNTS = {
    "needs_review": 5,
    "approved": 3,
    "published": 3,
    "rejected": 2,
    "archived": 2,
    "total": 15,
}

# First needs_review event ID (used in action tests)
NEEDS_REVIEW_IDS = [str(_uuid(i)) for i in range(1, 6)]
APPROVED_IDS = [str(_uuid(i)) for i in range(6, 9)]
PUBLISHED_IDS = [str(_uuid(i)) for i in range(9, 12)]
